###Calculate BLUE for phenotypes
library(lme4)
library(lsmeans)
dat <- read.table("F:/wheat/phenotype/phe.txt",header = T)
#View(dat)
str(dat)
for(i in 1:4) dat[,i] = as.factor(dat[,i])
dat[,5] = as.numeric(dat[,5]) 
str(dat)
library(lme4)
m1=lmer(phe~Line +(1|Location)+(1+Year)+(1|Location:Rep), data=dat)
as.data.frame(fixef(m1))
re = lsmeans(m1,"Line") 
head(re)
write.table(re, "phe_BLUE.txt", sep=" ")
q()
